services:
  django:
    build: .
    command: daphne -b 0.0.0.0 -p 8000 unichat.asgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://redis:6379/1 # Connects to the Redis service
    restart: always
  
  redis:
    image: redis:7-alpine # Use a lightweight Redis image
    container_name: unichat_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data # Persist Redis data

volumes:
  redis_data:
